### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by 3zzy** [erodner/giss#1]
Traceback (most recent call last):
  File "gis-scrape.py", line 187, in <module>
    parse_options = libxml2.HTML_PARSE_RECOVER + libxml2.HTML_PARSE_NOERROR + libxml2.HTML_PARSE_NOWARNING
AttributeError: 'module' object has no attribute 'HTML_PARSE_RECOVER'

**Comment by erodner** [comment]
Your error is likely due to an older version of libxml2. What version are you using?
The version on my current system is 2.9.0.
https://groups.google.com/forum/#!msg/scrapy-users/GVSiAw7tvCM/h1XFRzfpU5EJ
